### ISSUE TITLE
Option to define prefix/namespace for metrics when using Prometheus

### ISSUE THREAD

**Issue by hvancamp** [xenit-eu/alfred-telemetry#21]
There doesn't seem to be an way to define a prefix/namespace for the Alfred Telemetry metrics when using Prometheus?

This option would make it easier to identify the metrics provided by Alfred Telemetry (for Alfresco) in Prometheus.

e.g. to use "**alfresco**.jdbc.connection.count" instead of "jdbc.connections.count"

see also the Prometheus docs [naming practices:](https://prometheus.io/docs/practices/naming/)

> A metric name...
> ...should have a (single-word) application prefix relevant to the domain the metric belongs to. The prefix is sometimes referred  to as namespace by client libraries. For metrics specific to an application, the prefix is usually the application name itself.

**Comment by tgeens** [comment]
That functionality is built into micrometer, let me have a look if we expose that or not.

Not 100% convinced about the "best practice" at this point.

**Comment by tgeens** [comment]
@hvancamp That uneasy feeling I had about that "best practice" appears to have some grounds. You left out some important parts in the quoted the piece ? :-) 

> For metrics specific to an application, the prefix is usually the application name itself.

Right.

But see what follows:

> Sometimes, however, metrics are more generic, like standardized metrics exported by client libraries. Examples:

Specific example:
> prometheus_notifications_total (specific to the Prometheus server)

Generic example:
> process_cpu_seconds_total (exported by many client libraries)
> http_request_duration_seconds (for all HTTP requests)

`jdbc.connection.count` falls right into that last category, right ?

Just slapping an application prefix in front of all metric names is not the appropriate solution, in my opinion. Prometheus has a dimensional data model - which means you add key/value tags to the time series. The idiomatic way to access metrics for alfresco would be `jdbc.connections.count{application = "alfresco", ....}` (you will need a couple more selectors anyway)

This is in contrast with an hierarchical system, like graphite, were you have to put all the tags in the metric-name.

-- 

After all of that - we maybe should still expose a prefix-config-setting for Prometheus registries - but this is possibly not a good use case for that :-)

Thoughts @kerkhofsd ?

**Comment by hvancamp** [comment]
I see Alfred Telemetry as another Prometheus exporter and so far in the metrics provided by haproxy builtin Prometheus exporter or pgwatch2, they always add an application prefix which I find super handy to filter on when writing Prometheus expressions or when creating dashboards in Grafana for example.

**Comment by tgeens** [comment]
I don't think you are correct there. Sure pgwatch exposes some `pgwatch2_*` metrics that are specific for pgwatch.
But it also exports a bunch of geneirc `go_*` metrics, example query: `go_gc_duration_seconds{job="pgwatch"}

That is fully in line with the 'best practices'.

This is further explained here: https://www.robustperception.io/target-labels-not-metric-name-prefixes
Credits to @kerkhofsd for the link

**Comment by hvancamp** [comment]
Okay. Good point. Didn't notice that pgwatch also had generic metrics without prefix. 

Going through the list of provided metrics by Alfred Telemetry, I still feel that metrics like:

* cache
* users
* solr sharding

Could use a prefix, I don't consider them as generic metrics, they are very specific to Alfresco ...

**Comment by vierbergenlars** [comment]
> That is fully in line with the 'naming practices' link you provided: specialized with prefix, generic without prefix

The generic ones still have a prefix, namely `go_` or `jdbc_` in these cases.

It is key that a metric with a certain name always provides the same kind of data and always has the same metrics under its prefix. For example, `jdbc_connections_count` is always the number of JDBC connections for any application. It's a metric provided by a generic library that is used in a lot of different applications, and it always exposes the same metrics.

However, cache and solr sharding are not generic. Both can have very different metrics with that prefix depending on the application (let's say we're running something else that also uses sharded solr), and thus should be prefixed with `alfresco_`

**Comment by tgeens** [comment]
Agreed for the solr sharding metrics.

Don't think I agree about the cache-metrics, because those are the default
metric names in micrometer and also ship like that with Spring Boot.
Cache get/push/miss counts/timings is pretty generic ?

Kind regards,

Toon Geens

XeniT Solutions NV - http://www.xenit.eu
Diestsevest 32, 4A
B3000 Leuven
+32 16 891 801

**Comment by todorinskiz** [comment]
Let's take the old habits out first: Prometheus is **not** Graphite. The design revolves around labels.
The case @vierbergenlars is describing is a completely other scenario than what this issue was initially created for --> Grafana dashboards.
To simplify further, let's compare the two:

-  **alfresco**.jdbc.connection.count
- jdbc.connection.count**{application="alfresco"}**

With the first (namespaced) entry, afaik the data will be stored in completely different segment, splitting the time series from each other - hence the use case @vierbergenlars described makes sense.
The second case will mark individual entries with a specific label, making it easier to index.

I suggest we close this ticket until we actually need this, since the proposed application is rather cosmetic?
