### ISSUE TITLE
Error creating bean with name 'eu.xenit.alfred.telemetry.binder.solr.sharding.SolrShardingMetrics'

### ISSUE THREAD

**Issue by hvancamp** [xenit-eu/alfred-telemetry#37]
When I clicked on revert for the mbean "Alfresco:Category=Search,Type=Configuration,id1=managed,id2=solr4" on the Alfresco admin-console, jmx settings, it generates an HTTP 500 with the following exception:

`10050214 Wrapped Exception (with status template): 10055569 Failed to execute script 'classpath*:alfresco/enterprise/webscripts/org/alfresco/enterprise/repository/admin/support-tools/admin-jmx-settings.post.js': java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eu.xenit.alfred.telemetry.binder.solr.sharding.SolrShardingMetrics': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [eu.xenit.alfred.telemetry.binder.solr.sharding.SolrShardingMetricsFactory]: Constructor threw exception; nested exception is org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'DEFAULT.SolrShardingMetricsJob', because one already exists with this identification.`

**Comment by TomVerschuerenXenit** [comment]
`/**
     * Schedule all of the given jobs with the related set of triggers.
     * 
     * <p>If any of the given jobs or triggers already exist (or more
     * specifically, if the keys are not unique) and the replace 
     * parameter is not set to true then an exception will be thrown.</p>
     * 
     * @throws ObjectAlreadyExistsException if the job/trigger keys
     * are not unique and the replace flag is not set to true. 
     */
    void scheduleJobs(Map<JobDetail, Set<? extends Trigger>> triggersAndJobs, boolean replace) throws SchedulerException;`
`
Maybe we should set the replace flag to true? Although according to the documentation, it should throw a SchedulerException instead of a ObjectAlreadyExistsException since the following method is used:

`    /**
     * Add the given <code>{@link org.quartz.JobDetail}</code> to the
     * Scheduler, and associate the given <code>{@link Trigger}</code> with
     * it.
     * 
     * <p>
     * If the given Trigger does not reference any <code>Job</code>, then it
     * will be set to reference the Job passed with it into this method.
     * </p>
     * 
     * @throws SchedulerException
     *           if the Job or Trigger cannot be added to the Scheduler, or
     *           there is an internal Scheduler error.
     */
    Date scheduleJob(JobDetail jobDetail, Trigger trigger)
        throws SchedulerException;

@tgeens @thijslemmens `

**Comment by thijslemmens** [comment]
I think we have to deregister the shceduled job when the subsystem goes down. Because the "revert" will probably trigger a restart of the subsystem, again registering the same job.

**Comment by TomVerschuerenXenit** [comment]
This ones for you. I have no idea how to implement that what you said without wasting tons of time figuring it out. Please add me to the review if you ever find time to implement it. This way I can view and learn a little more about it.

**Comment by tgeens** [comment]
@TomVerschuerenXenit it's fine to spend some time, that's how you learn ;-)

Subsystems in Alfresco are separate Spring child-contexts, which can be stopped, changed, restarted, ... at runtime. When you make config changes through the Alfresco admin dashboard, that's basically how that happens.

When the search-subsystem is started a bean named `SolrShardingMetricsFactory` is created, which registers a job with the `Scheduler` from the main Spring-application-context. (The `-Factory`-part is a bit of an unfortunate name, because it's not a Spring-bean-factory).

What needs to be changed - that `SolrShardingMetricsFactory` now registers a scheduled job in it's constructor, which is invoked when the search-subsyste/child-context is initialized. We need to unregister that same job when the child-context is destroyed.

That bean-definition for the `SolrShardingMetricsFactory` is not in xml, but created programatically in `SolrMetricsBeanPostProcessor`. You can configure a `destroy-method` on that bean definition and a method with that name will be invoked when the child-context is destroyed.

Reference:
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/support/AbstractBeanDefinition.html#setDestroyMethodName-java.lang.String-

**Comment by thijslemmens** [comment]
Yes, go ahead changing the name. I did not come up with anything better.

Op vr 13 nov. 2020 om 10:48 schreef Toon Geens <notifications@github.com>:
